<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net8.0-windows10.0.19041.0;net8.0-android;net8.0-ios;net8.0-maccatalyst</TargetFrameworks>
		<OutputType>Exe</OutputType>
		<RootNamespace>CMS.Maui</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
      <WindowsPackageType>MSIX</WindowsPackageType>
      <WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
      <ApplicationTitle>CMS.Maui</ApplicationTitle>
		<ApplicationId>com.companyname.cms.maui</ApplicationId>
		<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
		<ApplicationVersion>1</ApplicationVersion>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">11.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">13.1</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">21.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
		<TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>

	</PropertyGroup>

	<ItemGroup>
		<!-- App Icon -->
		<MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" Color="#512BD4" />
		<MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#512BD4" BaseSize="128,128" />
		<MauiImage Include="Resources\Images\*" />
		<MauiImage Update="Resources\Images\dotnet_bot.png" Resize="True" BaseSize="300,185" />
		<MauiFont Include="Resources\Fonts\*" />

		<!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>

   <ItemGroup>
      <PackageReference Include="Microsoft.Maui.Controls" Version="*" />
      <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="8.0.1" />
      <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
      <PackageReference Include="Refit" Version="8.0.0" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
      <PackageReference Include="Microsoft.Extensions.Http" Version="8.0.1" />
      <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.7.240802000" />
   </ItemGroup>
   
	<ItemGroup>
	  <ProjectReference Include="..\CMS.Domain\CMS.Domain.csproj" />
	  <ProjectReference Include="..\CMS.Shared\CMS.Shared.csproj" />
	</ItemGroup>
   <ItemGroup>
      <Compile Update="CustomerPage.xaml.cs">
         <DependentUpon>CustomersPage.xaml</DependentUpon>
      </Compile>
   </ItemGroup>
   <ItemGroup>
      <MauiXaml Update="CustomerPage.xaml">
         <Generator>MSBuild:Compile</Generator>
      </MauiXaml>
   </ItemGroup>
   <ItemGroup>
      <MauiXaml Update="MainPage.xaml">
         <Generator>MSBuild:Compile</Generator>
      </MauiXaml>
      <MauiXaml Update="CustomerPage.xaml">
         <Generator>MSBuild:Compile</Generator>
      </MauiXaml>
   </ItemGroup>
</Project>
